### ISSUE TITLE
No build

### ISSUE THREAD

**Issue by Clippy95** [Lyall/DMCHDFix#1]
I am not sure if this is WIP but there appears to be no public build, and I can't compile it due to it most likely requiring Intel compiler which I don't want to install, thanks.

**Comment by Lyall** [comment]
Yes it's still a work-in-progress atm. I should be able to get a public release build out soon once I squash some of the more obvious bugs. I'll put up a notice on the readme stating this too. 

If you want, I can provide a test build for you if you'd be up for giving some feedback. At the moment I'm mainly trying to get rid of any show-stopper bugs.

Edit: Also yeah the Intel compiler requirement is annoying but it's the only way to get inline assembly using x64. I should really switch to using external assembly with NASM or something but that would be a big workflow change.

**Comment by Clippy95** [comment]
> If you want, I can provide a test build for you if you'd be up for giving some feedback. At the moment I'm mainly trying to get rid of any show-stopper bugs.

Sure I wouldn't mind.

**Comment by Lyall** [comment]
> > If you want, I can provide a test build for you if you'd be up for giving some feedback. At the moment I'm mainly trying to get rid of any show-stopper bugs.
> 
> Sure I wouldn't mind.

Here it is. Just download and then extract the zip to the game folder.

[DMCHDFix_v0_7_pre.zip](https://github.com/Lyall/DMCHDFix/files/13061704/DMCHDFix_v0_7_pre.zip)

**Comment by Chachardus** [comment]
I reinstalled the game on Steam to test your patch (resolution 3440x1440, i912900K, 3090Ti 64Go RAM, Windows 11 professional 22H2). dmc1.exe and dmc3.exe seem to work flawlessly, but dmc2.exe is crashing at launch.

**Comment by Lyall** [comment]
> I reinstalled the game on Steam to test your patch (resolution 3440x1440, i912900K, 3090Ti 64Go RAM, Windows 11 professional 22H2). dmc1.exe and dmc3.exe seem to work flawlessly, but dmc2.exe is crashing at launch.

The DMC2 crashing issue will be fixed in the next version. I should be uploading that later today.

**Comment by Lyall** [comment]
All right that's the public release build up now. Should fix the DMC2 crashing that @Chachardus mentioned. 

I'll close this issue for now, but feel free to open any new issues for anything you catch that isn't already on the known issues list.
